export const TICK_MS = 60_000;
export const categories = [
  {id:1,name:'Achadinhos',cap:15,shipping:1,unlock:0,goal:0,products:[
    ['organizador','Organizador de Cabos','🗂️',12,1,.85,.96,.6,10],['adesivos','Kit de Adesivos','🎨',8,1,1.2,.97,.7,12],['chaveiro','Chaveiro LED','🔦',14,1,.9,.91,.8,9],['suporte','Suporte para Celular','📱',13,1,1.1,.95,.8,10],['marcador','Marca-páginas Magnético','📖',6,1,.8,.98,.5,10]]},
  {id:2,name:'Utilidades',cap:40,shipping:2,unlock:500,goal:30,products:[
    ['garrafa','Garrafa Térmica 1L','🧃',29,2,1.1,.93,.85,8],['lamp','Luminária de Lua','🌙',38,2,1.15,.88,.7,7],['caneca','Caneca Térmica','☕',32,2,1.05,.94,.8,8],['necessaire','Nécessaire de Viagem','🧳',25,1,.9,.95,.6,7],['mousepad','Mousepad Grande','🖱️',35,2,1.1,.9,.8,8]]},
  {id:3,name:'Acessórios',cap:100,shipping:3,unlock:2000,goal:80,products:[
    ['fone','Fone Bluetooth X9','🎧',54,1,1.2,.7,1.2,10],['pet','Fonte para Gatos','🐈',49,2,1.3,.82,.55,7],['massageador','Massageador Compacto','💆',74,2,1.05,.87,.7,6],['mochila','Mochila Urbana','🎒',89,3,1.1,.92,.8,7],['camera','Câmera Wi-Fi','📷',99,2,1.15,.85,.9,7]]},
  {id:4,name:'Eletrônicos',cap:500,shipping:5,unlock:10000,goal:160,products:[
    ['teclado','Teclado Mecânico RGB','⌨️',98,3,.95,.84,.9,5],['projetor','Mini Projetor Portátil','📽️',190,4,1.4,.72,1.05,4],['tablet','Tablet Compacto','💻',420,3,1.2,.85,1.1,5],['robo','Robô Aspirador','🤖',350,5,1.15,.86,.9,5],['console','Console Retrô','🎮',290,3,1.3,.87,1,6]]},
  {id:5,name:'Premium',cap:5000,shipping:8,unlock:75000,goal:300,products:[
    ['drone','Drone 4K','🚁',2100,4,1.2,.86,1,4],['notebook','Notebook Pro','💻',4800,4,1.2,.9,1.2,4],['camera_pro','Câmera Profissional','📸',3900,4,.9,.93,.8,3],['relogio','Relógio de Luxo','⌚',3200,2,1.05,.95,.9,4],['bike','Bicicleta Elétrica','🚲',4900,7,1.1,.89,.9,3]]},
  {id:6,name:'Veículos e luxo',cap:Infinity,shipping:12,unlock:300000,goal:500,products:[
    ['carro_esportivo','Carro Esportivo','🏎️',420000,1,1.1,.98,1.2,3],['carro_eletrico','Carro Elétrico de Luxo','🚘',350000,1,1.15,.98,1.1,3],['suv','SUV Premium','🚙',280000,1,1.1,.97,1,3],['iate','Lancha de Luxo','🛥️',620000,1,.9,.98,1.2,2],['classico','Carro Clássico','🚗',190000,1,.85,.96,.8,2]]}
];
export const products=categories.flatMap(c=>c.products.map(([id,name,emoji,cost,space,trend,quality,competition,base])=>({id,name,emoji,cost,space,trend,quality,competition,base,categoryId:c.id,category:c.name,garage:c.id===6})));
export const upgrades={marketing:{name:'Marketing',costs:[700,1800,4200],effect:'Mais visitantes por ciclo'},conversion:{name:'Conversão',costs:[850,2200,5000],effect:'Mais visitantes viram compradores'},retention:{name:'Retenção',costs:[900,2400,5500],effect:'Compradores levam mais unidades'},shipping:{name:'Frete',costs:[750,1900,4500],effect:'Prazo e custo menores nos próximos pedidos'}};
export const warehouseSizes=[20,40,80,160,320,640];
export const warehouseCosts=[450,1500,5000,18000,65000];
export const garageSizes=[2,4,8];
export const garageCosts=[60000,180000];
export function newGame(now=Date.now()){return {version:3,minute:0,lastTick:now,cash:3000,debt:0,reputation:4.5,capacity:20,garageCapacity:0,stock:{},incoming:[],listings:{},unlocked:1,levels:{marketing:0,conversion:0,retention:0,shipping:0},transactions:[{minute:0,label:'Capital inicial',amount:3000}],history:[],reports:[],totals:{visits:0,buyers:0,orders:0,units:0,revenue:0,fees:0,missed:0},feed:['Bem-vindo! Compre um lote de Achadinhos. Anuncie quando ele chegar.'],research:{},seed:Math.floor(Math.random()*2147483647)||1}}
export function migrate(data,now=Date.now()){if(!data||typeof data.cash!=='number'||!data.stock)return newGame(now);if(data.version===3)return data;const base=newGame(now);const owned=Object.keys(data.stock||{}).concat((data.incoming||[]).map(o=>o.id),Object.keys(data.listings||{}));const unlocked=Math.max(1,...owned.map(id=>products.find(p=>p.id===id)?.categoryId||1));const oldCapacity=data.capacity||20;return {...base,cash:data.cash,debt:data.debt||0,reputation:data.reputation||4.5,capacity:Math.max(20,oldCapacity),garageCapacity:unlocked>=6?2:0,stock:data.stock,incoming:(data.incoming||[]).map(o=>({...o,eta:typeof o.eta==='number'&&o.eta>1e12?o.eta:now+Math.max(1,(o.eta-(data.day||1)))*2*TICK_MS})),research:data.research||{},seed:data.seed||base.seed,minute:data.minute||0,lastTick:data.lastTick||now,feed:['Categorias, depósito e relatórios foram adicionados. Seus itens anteriores foram preservados.',...(data.feed||[])].slice(0,30),listings:data.listings||{},levels:data.levels||base.levels,unlocked,transactions:(data.transactions||base.transactions).slice(0,120),history:(data.history||[]).slice(-60)}}
export const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n||0);
const product=id=>products.find(p=>p.id===id);
export const occupied=s=>Object.entries(s.stock).reduce((sum,[id,n])=>sum+(product(id)?.garage?0:product(id)?.space||0)*n,0);
export const reserved=s=>s.incoming.reduce((sum,o)=>sum+(product(o.id)?.garage?0:product(o.id)?.space||0)*o.qty,0);
export const garageOccupied=s=>Object.entries(s.stock).reduce((sum,[id,n])=>sum+(product(id)?.garage?n:0),0);
export const garageReserved=s=>s.incoming.reduce((sum,o)=>sum+(product(o.id)?.garage?o.qty:0),0);
export const wealth=s=>s.cash-s.debt+Object.entries(s.stock).reduce((sum,[id,n])=>sum+(product(id)?.cost||0)*n,0)+s.incoming.reduce((sum,o)=>sum+(product(o.id)?.cost||0)*o.qty,0);
export const deliveryMinutes=(p,level=0)=>Math.max(1,Math.ceil(categories[p.categoryId-1].shipping*(1-Math.min(level,3)*.15)));
export const freightCost=(p,qty,level=0)=>Math.ceil((8+Math.ceil(qty/10)*2)*p.categoryId*(1-Math.min(level,3)*.12));
function random(seed){const next=(Math.imul(seed,1664525)+1013904223)>>>0;return [next,next/4294967296]}
export function buy(s,id,qty,now=Date.now()){const p=product(id);qty=Number(qty);if(!p||p.categoryId>s.unlocked)return [s,'Desbloqueie esta categoria antes de comprar.'];if(!Number.isInteger(qty)||qty<1||qty>200)return [s,'Escolha uma quantidade inteira entre 1 e 200.'];const total=p.cost*qty+freightCost(p,qty,s.levels.shipping);if(total>s.cash)return [s,'Saldo insuficiente para o lote e o frete.'];if(p.garage?garageOccupied(s)+garageReserved(s)+qty>s.garageCapacity:occupied(s)+reserved(s)+qty*p.space>s.capacity)return [s,p.garage?'Seu pátio não tem vaga para esse lote.':'Seu depósito não tem espaço para esse lote.'];const eta=now+deliveryMinutes(p,s.levels.shipping)*TICK_MS;return [{...s,cash:s.cash-total,incoming:[...s.incoming,{id,qty,eta}],transactions:[{minute:s.minute,label:`Compra: ${qty}× ${p.name} + frete`,amount:-total},...s.transactions].slice(0,120),feed:[`Pedido de ${qty}× ${p.name} confirmado. Chega em ${deliveryMinutes(p,s.levels.shipping)} min.`,...s.feed].slice(0,30)},null]}
export function listProduct(s,id,price){const p=product(id);price=Number(price);if(!p||!Number.isFinite(price)||price<=0)return [s,'Informe um preço de venda válido.'];if(!(s.stock[id]>0))return [s,'É preciso ter pelo menos uma unidade em estoque para anunciar.'];return [{...s,listings:{...s.listings,[id]:{price:Math.round(price*100)/100,active:true}},feed:[`Anúncio de ${p.name} publicado por ${money(price)}.`,...s.feed].slice(0,30)},null]}
export function unlock(s,id){const c=categories[id-1];if(!c||id!==s.unlocked+1)return [s,'Desbloqueie a próxima categoria na sequência.'];const sold=categories[id-2].products.reduce((sum,[pid])=>sum+(s.research[pid]||0),0);if(sold<c.goal)return [s,`Venda mais ${c.goal-sold} unidade(s) da categoria anterior.`];if(s.cash<c.unlock)return [s,'Saldo insuficiente para desbloquear a categoria.'];return [{...s,cash:s.cash-c.unlock,unlocked:id,garageCapacity:id===6?2:s.garageCapacity,transactions:[{minute:s.minute,label:`Desbloqueio: ${c.name}`,amount:-c.unlock},...s.transactions].slice(0,120),feed:[`${c.name} desbloqueada! Novos produtos disponíveis.`,...s.feed].slice(0,30)},null]}
export function expandWarehouse(s){const next=warehouseSizes.findIndex(size=>size>s.capacity),cost=warehouseCosts[next-1];if(cost==null)return [s,'Depósito no tamanho máximo.'];if(s.cash<cost)return [s,'Saldo insuficiente para ampliar o depósito.'];return [{...s,cash:s.cash-cost,capacity:warehouseSizes[next],transactions:[{minute:s.minute,label:`Ampliação do depósito para ${warehouseSizes[next]}`,amount:-cost},...s.transactions].slice(0,120),feed:[`Depósito ampliado para ${warehouseSizes[next]} espaços.`,...s.feed].slice(0,30)},null]}
export function expandGarage(s){if(s.unlocked<6)return [s,'Desbloqueie Veículos e luxo primeiro.'];const next=garageSizes.indexOf(s.garageCapacity)+1,cost=garageCosts[next-1];if(cost==null)return [s,'Pátio no tamanho máximo.'];if(s.cash<cost)return [s,'Saldo insuficiente para ampliar o pátio.'];return [{...s,cash:s.cash-cost,garageCapacity:garageSizes[next],transactions:[{minute:s.minute,label:`Ampliação do pátio para ${garageSizes[next]} vagas`,amount:-cost},...s.transactions].slice(0,120),feed:[`Pátio ampliado para ${garageSizes[next]} vagas.`,...s.feed].slice(0,30)},null]}
export function upgrade(s,type){const item=upgrades[type],level=s.levels[type],cost=item?.costs[level];if(cost==null)return [s,'Este upgrade já está no nível máximo.'];if(s.cash<cost)return [s,'Saldo insuficiente para este upgrade.'];return [{...s,cash:s.cash-cost,levels:{...s.levels,[type]:level+1},transactions:[{minute:s.minute,label:`Upgrade: ${item.name} nível ${level+1}`,amount:-cost},...s.transactions].slice(0,120),feed:[`${item.name} melhorado para nível ${level+1}.`,...s.feed].slice(0,30)},null]}
export function loan(s){if(s.debt)return [s,'Quite o crédito atual antes de pedir outro.'];return [{...s,cash:s.cash+750,debt:900,transactions:[{minute:s.minute,label:'Crédito de recuperação',amount:750},...s.transactions].slice(0,120),feed:['Crédito de R$ 750 recebido. Quite R$ 900 quando puder.',...s.feed].slice(0,30)},null]}
export function repay(s){if(!s.debt||s.cash<s.debt)return [s,'Você precisa ter saldo suficiente para quitar toda a dívida.'];return [{...s,cash:s.cash-s.debt,debt:0,transactions:[{minute:s.minute,label:'Quitação do crédito',amount:-s.debt},...s.transactions].slice(0,120),feed:['Crédito quitado.',...s.feed].slice(0,30)},null]}
const firstNames=['Marina','Rafael','Camila','Bruno','Lívia','André','Paula','Diego','Bianca','Felipe','Sofia','Lucas','Julia','Mateus','Ana','Pedro'];
const lastInitials='ASMCPLRFTDBGVN';
function tick(s,time){let seed=s.seed,cash=s.cash,stock={...s.stock},reputation=s.reputation,feed=[],transactions=[],research={...s.research};const rand=()=>{let v;[seed,v]=random(seed);return v};let arrivals=0,visits=0,buyers=0,sales=0,revenue=0,fees=0,missed=0,defects=0;const minute=s.minute+1,incoming=[],orders=[],byProduct=[];
  for(const order of s.incoming){if(order.eta>time){incoming.push(order);continue}const p=product(order.id);if(!p)continue;let broken=0;for(let i=0;i<order.qty;i++)if(rand()>p.quality)broken++;stock[p.id]=(stock[p.id]||0)+order.qty-broken;arrivals+=order.qty-broken;defects+=broken;feed.push(`${p.emoji} ${order.qty-broken} ${p.name} chegaram${broken?` (${broken} com defeito)`:''}.`)}
  const available=products.filter(p=>s.listings[p.id]?.active&&stock[p.id]>0);
  const metrics=Object.fromEntries(available.map(p=>[p.id,{id:p.id,name:p.name,emoji:p.emoji,visits:0,buyers:0,units:0,revenue:0,missed:0}]));
  for(const p of available){
    const listing=s.listings[p.id],audience=Math.max(0,Math.round(p.base*p.trend*(.6+rand()*.8)*(1+s.levels.marketing*.4)/(.7+p.competition*.35)));
    visits+=audience;metrics[p.id].visits=audience;
    const priceFactor=Math.max(.25,Math.min(1.5,(p.cost*2.1)/listing.price)),chance=Math.min(.65,(.10+s.levels.conversion*.045)*priceFactor*(reputation/4.5));
    for(let i=0;i<audience;i++){
      if(rand()>=chance)continue;
      const quantity=1+(rand()<(.08+s.levels.retention*.12)?1:0)+(s.levels.retention>=3&&rand()<.1?1:0);
      const sold=Math.min(quantity,stock[p.id]);metrics[p.id].missed+=quantity-sold;missed+=quantity-sold;if(!sold)continue;
      const items=[{productId:p.id,product:p.name,emoji:p.emoji,quantity:sold,unitPrice:listing.price,total:sold*listing.price}];stock[p.id]-=sold;
      const others=available.filter(x=>x.id!==p.id&&stock[x.id]>0);
      if(others.length&&rand()<.08+s.levels.retention*.12){const extra=others[Math.floor(rand()*others.length)],extraListing=s.listings[extra.id];stock[extra.id]--;items.push({productId:extra.id,product:extra.name,emoji:extra.emoji,quantity:1,unitPrice:extraListing.price,total:extraListing.price})}
      for(const item of items){const m=metrics[item.productId];m.buyers++;m.units+=item.quantity;m.revenue+=item.total;research[item.productId]=(research[item.productId]||0)+item.quantity;sales+=item.quantity;revenue+=item.total}
      buyers++;orders.push({customer:`${firstNames[Math.floor(rand()*firstNames.length)]} ${lastInitials[Math.floor(rand()*lastInitials.length)]}.`,items,total:items.reduce((sum,item)=>sum+item.total,0)})
    }
  }
  byProduct.push(...Object.values(metrics));
  for(const m of byProduct){if(m.units){const fee=Math.round(m.revenue*.12*100)/100;fees+=fee;cash+=m.revenue-fee;transactions.push({minute,label:`Vendas: ${m.units}× ${m.name} (taxa inclusa)`,amount:m.revenue-fee});feed.push(`${m.emoji} ${m.units}× ${m.name} vendidos: ${money(m.revenue-fee)} líquidos.`)}if(m.missed)feed.push(`${m.emoji} ${m.name}: ${m.missed} unidade(s) pedida(s) sem estoque.`)}
  if(defects)reputation=Math.max(2.5,Math.round((reputation-defects*.012)*100)/100);if(!feed.length)feed.push(`Ciclo ${minute}: ${visits} visitas, nenhuma compra desta vez.`);
  const report={minute,time,visits,buyers,orders,units:sales,revenue,fees,received:revenue-fees,missed,arrivals,defects,byProduct};const totals={visits:s.totals.visits+visits,buyers:s.totals.buyers+buyers,orders:s.totals.orders+orders.length,units:s.totals.units+sales,revenue:s.totals.revenue+revenue,fees:s.totals.fees+fees,missed:s.totals.missed+missed};
  return {...s,minute,cash,stock,incoming,reputation,transactions:[...transactions,...s.transactions].slice(0,120),history:[...s.history,{minute,visits,buyers,sales,revenue,fees,arrivals,missed,cash}].slice(-60),reports:[report,...s.reports].slice(0,120),totals,feed:[...feed,...s.feed].slice(0,30),research,seed,lastTick:time}
}
export function settle(s,now=Date.now()){if(now<s.lastTick)return s;const due=Math.floor((now-s.lastTick)/TICK_MS);if(!due)return s;let next=s;for(let i=0;i<Math.min(due,10080);i++)next=tick(next,next.lastTick+TICK_MS);if(due>10080)next={...next,lastTick:now-TICK_MS};return next}
