export const products = [
  {id:'lamp',name:'Luminária de Lua',category:'Casa',emoji:'🌙',cost:38,space:2,trend:1.15,quality:.88,competition:.7,base:7},
  {id:'fone',name:'Fone Bluetooth X9',category:'Eletrônicos',emoji:'🎧',cost:54,space:1,trend:1.2,quality:.7,competition:1.2,base:10},
  {id:'garrafa',name:'Garrafa Térmica 1L',category:'Casa',emoji:'🧃',cost:29,space:2,trend:1.1,quality:.93,competition:.85,base:8},
  {id:'teclado',name:'Teclado Mecânico RGB',category:'Eletrônicos',emoji:'⌨️',cost:98,space:3,trend:.95,quality:.84,competition:.9,base:5},
  {id:'pet',name:'Fonte para Gatos',category:'Pets',emoji:'🐈',cost:49,space:2,trend:1.3,quality:.82,competition:.55,base:7},
  {id:'organizador',name:'Organizador de Cabos',category:'Escritório',emoji:'🗂️',cost:12,space:1,trend:.85,quality:.96,competition:.6,base:10},
  {id:'projetor',name:'Mini Projetor Portátil',category:'Eletrônicos',emoji:'📽️',cost:190,space:4,trend:1.4,quality:.72,competition:1.05,base:4},
  {id:'massageador',name:'Massageador Compacto',category:'Bem-estar',emoji:'💆',cost:74,space:2,trend:1.05,quality:.87,competition:.7,base:6},
];
export const TICK_MS=60_000;
export const upgrades={marketing:{name:'Marketing',costs:[700,1800,4200],effect:'Mais visitantes por ciclo'},conversion:{name:'Conversão',costs:[850,2200,5000],effect:'Mais visitantes viram compradores'},retention:{name:'Retenção',costs:[900,2400,5500],effect:'Compradores levam mais unidades'},shipping:{name:'Frete',costs:[750,1900,4500],effect:'Lotes chegam mais rápido'}};
export function newGame(now=Date.now()){return {version:2,minute:0,lastTick:now,cash:3000,debt:0,reputation:4.5,capacity:100,stock:{},incoming:[],listings:{},levels:{marketing:0,conversion:0,retention:0,shipping:0},transactions:[{minute:0,label:'Capital inicial',amount:3000}],history:[],feed:['Bem-vindo! Compre estoque no Dragão Express. Anuncie no Merca Livre quando ele chegar.'],research:{},seed:Math.floor(Math.random()*2147483647)||1}}
export function migrate(data,now=Date.now()){if(!data||typeof data.cash!=='number'||!data.stock)return newGame(now);if(data.version===2)return data;const base=newGame(now);return {...base,cash:data.cash,debt:data.debt||0,reputation:data.reputation||4.5,capacity:data.capacity||100,stock:data.stock,incoming:(data.incoming||[]).map(o=>({...o,eta:now+Math.max(1,(o.eta-(data.day||1)))*2*TICK_MS})),research:data.research||{},seed:data.seed||base.seed,feed:['O jogo agora avança automaticamente a cada minuto. Anúncios antigos sem estoque foram pausados.',...(data.feed||[])].slice(0,30),listings:Object.fromEntries(Object.entries(data.listings||{}).map(([id,l])=>[id,{price:l.price,active:!!data.stock[id]}]))}}
export const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n||0);
export const occupied=s=>Object.entries(s.stock).reduce((sum,[id,n])=>sum+(products.find(p=>p.id===id)?.space||1)*n,0);
export const reserved=s=>s.incoming.reduce((sum,o)=>sum+(products.find(p=>p.id===o.id)?.space||1)*o.qty,0);
export const wealth=s=>s.cash-s.debt+Object.entries(s.stock).reduce((sum,[id,n])=>sum+(products.find(p=>p.id===id)?.cost||0)*n,0)+s.incoming.reduce((sum,o)=>sum+(products.find(p=>p.id===o.id)?.cost||0)*o.qty,0);
export const deliveryMinutes=(p,level)=>Math.max(1,(p.cost>100?7:5)-level);
function random(seed){const next=(Math.imul(seed,1664525)+1013904223)>>>0;return [next,next/4294967296]}
export function buy(s,id,qty,now=Date.now()){const p=products.find(x=>x.id===id);qty=Number(qty);if(!p||!Number.isInteger(qty)||qty<1||qty>200)return [s,'Escolha uma quantidade inteira entre 1 e 200.'];const freight=28+Math.ceil(qty/10)*7,total=p.cost*qty+freight;if(total>s.cash)return [s,'Saldo insuficiente para o lote e o frete.'];if(occupied(s)+reserved(s)+qty*p.space>s.capacity)return [s,'Seu depósito não tem espaço para esse lote.'];const eta=now+deliveryMinutes(p,s.levels.shipping)*TICK_MS;return [{...s,cash:s.cash-total,incoming:[...s.incoming,{id,qty,eta}],transactions:[{minute:s.minute,label:`Compra: ${qty}× ${p.name} + frete`,amount:-total},...s.transactions].slice(0,120),feed:[`Pedido de ${qty}× ${p.name} confirmado. Chega em ${deliveryMinutes(p,s.levels.shipping)} min.`,...s.feed].slice(0,30)},null]}
export function listProduct(s,id,price){const p=products.find(x=>x.id===id);price=Number(price);if(!p||!Number.isFinite(price)||price<=0)return [s,'Informe um preço de venda válido.'];if(!(s.stock[id]>0))return [s,'É preciso ter pelo menos uma unidade em estoque para anunciar.'];return [{...s,listings:{...s.listings,[id]:{price:Math.round(price*100)/100,active:true}},feed:[`Anúncio de ${p.name} publicado por ${money(price)}.`,...s.feed].slice(0,30)},null]}
export function upgrade(s,type){const item=upgrades[type],level=s.levels[type],cost=item?.costs[level];if(cost==null)return [s,'Este upgrade já está no nível máximo.'];if(s.cash<cost)return [s,'Saldo insuficiente para este upgrade.'];return [{...s,cash:s.cash-cost,levels:{...s.levels,[type]:level+1},transactions:[{minute:s.minute,label:`Upgrade: ${item.name} nível ${level+1}`,amount:-cost},...s.transactions].slice(0,120),feed:[`${item.name} melhorado para nível ${level+1}.`,...s.feed].slice(0,30)},null]}
export function loan(s){if(s.debt)return [s,'Quite o crédito atual antes de pedir outro.'];return [{...s,cash:s.cash+750,debt:900,transactions:[{minute:s.minute,label:'Crédito de recuperação',amount:750},...s.transactions].slice(0,120),feed:['Crédito de R$ 750 recebido. Quite R$ 900 quando puder.',...s.feed].slice(0,30)},null]}
export function repay(s){if(!s.debt||s.cash<s.debt)return [s,'Você precisa ter saldo suficiente para quitar toda a dívida.'];return [{...s,cash:s.cash-s.debt,debt:0,transactions:[{minute:s.minute,label:'Quitação do crédito',amount:-s.debt},...s.transactions].slice(0,120),feed:['Crédito quitado.',...s.feed].slice(0,30)},null]}
function tick(s,time){let seed=s.seed,cash=s.cash,stock={...s.stock},reputation=s.reputation,feed=[],transactions=[],research={...s.research};const rand=()=>{let v;[seed,v]=random(seed);return v};let arrivals=0,visits=0,buyers=0,sales=0,revenue=0,fees=0,missed=0,defects=0;const minute=s.minute+1,incoming=[];
  for(const order of s.incoming){if(order.eta>time){incoming.push(order);continue}const p=products.find(x=>x.id===order.id);let broken=0;for(let i=0;i<order.qty;i++)if(rand()>p.quality)broken++;stock[p.id]=(stock[p.id]||0)+order.qty-broken;arrivals+=order.qty-broken;defects+=broken;feed.push(`${p.emoji} ${order.qty-broken} ${p.name} chegaram${broken?` (${broken} com defeito)`:''}.`)}
  for(const p of products){const listing=s.listings[p.id];if(!listing?.active)continue;if(!(stock[p.id]>0)){feed.push(`${p.emoji} ${p.name}: anúncio pausado por falta de estoque.`);continue}
    const audience=Math.max(0,Math.round(p.base*p.trend*(.6+rand()*.8)*(1+s.levels.marketing*.4)/(.7+p.competition*.35)));visits+=audience;const priceFactor=Math.max(.25,Math.min(1.5,(p.cost*2.1)/listing.price));const chance=Math.min(.65,(.10+s.levels.conversion*.045)*priceFactor*(reputation/4.5));let productBuyers=0,productSales=0;
    for(let i=0;i<audience;i++){if(rand()>=chance)continue;productBuyers++;const quantity=1+(rand()<(.08+s.levels.retention*.12)?1:0)+(s.levels.retention>=3&&rand()<.1?1:0);const sold=Math.min(quantity,stock[p.id]);missed+=quantity-sold;if(!sold)continue;stock[p.id]-=sold;productSales+=sold}
    buyers+=productBuyers;sales+=productSales;if(productSales){const gross=productSales*listing.price,fee=Math.round(gross*.12*100)/100;cash+=gross-fee;revenue+=gross;fees+=fee;transactions.push({minute,label:`Vendas: ${productSales}× ${p.name} (taxa inclusa)`,amount:gross-fee});research[p.id]=(research[p.id]||0)+productSales;feed.push(`${p.emoji} ${productSales}× ${p.name} vendidos para ${productBuyers} cliente(s): ${money(gross-fee)} líquidos.`)}
    if(missed&&stock[p.id]===0)feed.push(`${p.emoji} ${p.name}: estoque esgotado. O anúncio será pausado até a reposição.`)}
  if(defects)reputation=Math.max(2.5,Math.round((reputation-defects*.012)*100)/100);if(!feed.length)feed.push(`Ciclo ${minute}: ${visits} visitas, nenhuma compra desta vez.`);
  return {...s,minute,cash,stock,incoming,reputation,transactions:[...transactions,...s.transactions].slice(0,120),history:[...s.history,{minute,visits,buyers,sales,revenue,fees,arrivals,missed,cash}].slice(-60),feed:[...feed,...s.feed].slice(0,30),research,seed,lastTick:time}
}
export function settle(s,now=Date.now()){if(now<s.lastTick)return s;const due=Math.floor((now-s.lastTick)/TICK_MS);if(!due)return s;let next=s;for(let i=0;i<Math.min(due,10080);i++)next=tick(next,next.lastTick+TICK_MS);if(due>10080)next={...next,lastTick:now-TICK_MS};return next}
