export const products = [
  {id:'lamp',name:'Luminária de Lua',category:'Casa',emoji:'🌙',cost:38,space:2,trend:1.15,quality:.88,competition:.7,base:7},
  {id:'fone',name:'Fone Bluetooth X9',category:'Eletrônicos',emoji:'🎧',cost:54,space:1,trend:1.2,quality:.7,competition:1.2,base:10},
  {id:'garrafa',name:'Garrafa Térmica 1L',category:'Casa',emoji:'🧃',cost:29,space:2,trend:1.1,quality:.93,competition:.85,base:8},
  {id:'teclado',name:'Teclado Mecânico RGB',category:'Eletrônicos',emoji:'⌨️',cost:98,space:3,trend:.95,quality:.84,competition:.9,base:5},
  {id:'pet',name:'Fonte para Gatos',category:'Pets',emoji:'🐈',cost:49,space:2,trend:1.3,quality:.82,competition:.55,base:7},
  {id:'organizador',name:'Organizador de Cabos',category:'Escritório',emoji:'🗂️',cost:12,space:1,trend:.85,quality:.96,competition:.6,base:10},
  {id:'projetor',name:'Mini Projetor Portátil',category:'Eletrônicos',emoji:'📽️',cost:190,space:4,trend:1.4,quality:.72,competition:1.05,base:4},
  {id:'massageador',name:'Massageador Compacto',category:'Bem-estar',emoji:'💆',cost:74,space:2,trend:1.05,quality:.87,competition:.7,base:6},
];
export const initial = {day:1,cash:3000,debt:0,reputation:4.5,capacity:100,cooldownLevel:0,nextAdvance:0,stock:{},incoming:[],listings:{},transactions:[{day:1,label:'Capital inicial',amount:3000}],history:[],feed:['Bem-vindo! Encontre um produto, compre um lote e crie um anúncio.'],research:{},seed:Math.floor(Math.random()*2147483647)||1};
export const money = n => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n||0);
export const cooldowns = [300,240,180,120];
export const upgradeCosts = [1500,4000,10000];
export const occupied = s => Object.entries(s.stock).reduce((sum,[id,n])=>sum+(products.find(p=>p.id===id)?.space||1)*n,0);
export const reserved = s => s.incoming.reduce((sum,o)=>sum+(products.find(p=>p.id===o.id)?.space||1)*o.qty,0);
export const wealth = s => s.cash-s.debt+Object.entries(s.stock).reduce((sum,[id,n])=>sum+(products.find(p=>p.id===id)?.cost||0)*n,0)+s.incoming.reduce((sum,o)=>sum+(products.find(p=>p.id===o.id)?.cost||0)*o.qty,0);
function random(seed){const next=(Math.imul(seed,1664525)+1013904223)>>>0;return [next,next/4294967296]}
export function buy(s,id,qty){const p=products.find(x=>x.id===id);qty=Math.floor(Number(qty));if(!p||!Number.isFinite(qty)||qty<1||qty>200)return [s,'Escolha uma quantidade entre 1 e 200.'];const freight=28+Math.ceil(qty/10)*7,total=p.cost*qty+freight;if(total>s.cash)return [s,'Saldo insuficiente para o lote e o frete.'];if(occupied(s)+reserved(s)+qty*p.space>s.capacity)return [s,'Seu depósito não tem espaço para esse lote.'];const eta=s.day+2+(p.cost>100?1:0);return [{...s,cash:s.cash-total,incoming:[...s.incoming,{id,qty,eta}],transactions:[{day:s.day,label:`Compra: ${qty}× ${p.name} + frete`,amount:-total},...s.transactions],feed:[`Pedido de ${qty}× ${p.name} confirmado. Previsão: dia ${eta}.`,...s.feed].slice(0,30)},null]}
export function listProduct(s,id,price,ad){const p=products.find(x=>x.id===id);price=Number(price);ad=Math.floor(Number(ad));if(!p||!Number.isFinite(price)||price<=0||!Number.isFinite(ad)||ad<0||ad>500)return [s,'Confira o preço e a verba diária (R$ 0 a R$ 500).'];return [{...s,listings:{...s.listings,[id]:{price:Math.round(price*100)/100,ad,active:true}},feed:[`Anúncio de ${p.name} publicado por ${money(price)}.`,...s.feed].slice(0,30)},null]}
export function advance(s,now=Date.now()){if(now<s.nextAdvance)return [s,'Aguarde o cronômetro para avançar.'];let seed=s.seed, cash=s.cash, stock={...s.stock},reputation=s.reputation,feed=[],transactions=[],history=[],research={...s.research};const rand=()=>{let v;[seed,v]=random(seed);return v};let arrivals=0,sales=0,revenue=0,fees=0,ads=0,missed=0,defects=0;const day=s.day+1;const incoming=[];for(const order of s.incoming){if(order.eta>day){incoming.push(order);continue}const p=products.find(x=>x.id===order.id);let broken=0;for(let i=0;i<order.qty;i++)if(rand()>p.quality)broken++;stock[p.id]=(stock[p.id]||0)+order.qty-broken;arrivals+=order.qty-broken;defects+=broken;feed.push(`${p.emoji} ${order.qty-broken} ${p.name} chegaram${broken?` (${broken} com defeito)`:''}.`)}
  for(const p of products){const listing=s.listings[p.id];if(!listing?.active)continue;const spend=Math.min(listing.ad,Math.max(0,cash));cash-=spend;ads+=spend;if(spend)transactions.push({day,label:`Publicidade: ${p.name}`,amount:-spend});const market=0.6+rand()*.9;const priceFactor=Math.max(.12,Math.min(2.2,(p.cost*2.15)/listing.price));const boost=1+Math.sqrt(spend/25)*.4;const wanted=Math.max(0,Math.round(p.base*p.trend*market*priceFactor*boost/(.65+p.competition*.4)*(reputation/4.5)));const sold=Math.min(wanted,stock[p.id]||0);missed+=wanted-sold;if(wanted>sold)feed.push(`${p.emoji} ${p.name}: ${wanted-sold} venda(s) perdida(s) por falta de estoque.`);if(!sold)continue;stock[p.id]-=sold;const gross=sold*listing.price,fee=Math.round(gross*.12*100)/100;cash+=gross-fee;revenue+=gross;fees+=fee;sales+=sold;transactions.push({day,label:`Vendas: ${sold}× ${p.name} (taxa inclusa)`,amount:gross-fee});research[p.id]=(research[p.id]||0)+sold;feed.push(`${p.emoji} ${sold}× ${p.name} vendidos: ${money(gross-fee)} líquidos.`)}
  if(defects)reputation=Math.max(2.5,Math.round((reputation-defects*.012)*100)/100);
  if(!feed.length)feed.push('Dia tranquilo. Explore fornecedores ou prepare novos anúncios.');
  history=[...s.history,{day,sales,revenue,fees,ads,arrivals,missed,cash}].slice(-60);
  return [{...s,day,cash,stock,incoming,reputation,transactions:[...transactions,...s.transactions].slice(0,120),history,feed:[...feed,...s.feed].slice(0,30),research,seed,nextAdvance:now+cooldowns[s.cooldownLevel]*1000},null]
}
export function upgrade(s){const cost=upgradeCosts[s.cooldownLevel];if(cost==null)return [s,'A operação já está no nível máximo.'];if(s.cash<cost)return [s,'Saldo insuficiente para este upgrade.'];return [{...s,cash:s.cash-cost,cooldownLevel:s.cooldownLevel+1,transactions:[{day:s.day,label:'Upgrade de operação',amount:-cost},...s.transactions],feed:[`Operação melhorada! O intervalo agora é de ${cooldowns[s.cooldownLevel+1]/60} minutos.`,...s.feed].slice(0,30)},null]}
export function loan(s){if(s.debt)return [s,'Quite o crédito atual antes de pedir outro.'];return [{...s,cash:s.cash+750,debt:900,transactions:[{day:s.day,label:'Crédito de recuperação',amount:750},...s.transactions],feed:['Crédito de R$ 750 recebido. Quite R$ 900 quando puder.',...s.feed].slice(0,30)},null]}
export function repay(s){if(!s.debt||s.cash<s.debt)return [s,'Você precisa ter saldo suficiente para quitar toda a dívida.'];return [{...s,cash:s.cash-s.debt,debt:0,transactions:[{day:s.day,label:'Quitação do crédito',amount:-s.debt},...s.transactions],feed:['Crédito quitado.',...s.feed].slice(0,30)},null]}
