import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{ShoppingBag,Landmark,PackageSearch,Clock3,ArrowRight,TrendingUp,Plus,RotateCcw,Star,Info}from'lucide-react';
import{products,newGame,migrate,money,TICK_MS,upgrades,deliveryMinutes,occupied,reserved,wealth,buy,listProduct,settle,upgrade,loan,repay}from'./game';
import './style.css';
const KEY='merca-livre-sim-v1';
function load(){try{return settle(migrate(JSON.parse(localStorage.getItem(KEY))))}catch{return newGame()}}
function App(){
  const [s,setS]=useState(load),[tab,setTab]=useState('market'),[now,setNow]=useState(Date.now()),[selected,setSelected]=useState(null),[qty,setQty]=useState(10),[price,setPrice]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(s))},[s]);
  useEffect(()=>{const id=setInterval(()=>{const time=Date.now();setNow(time);setS(prev=>settle(prev,time))},1000);const onVisible=()=>{const time=Date.now();setNow(time);setS(prev=>settle(prev,time))};document.addEventListener('visibilitychange',onVisible);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',onVisible)}},[]);
  function act(fn,...args){const [next,error]=fn(settle(s,Date.now()),...args);setS(next);setNotice(error||'Feito!');setTimeout(()=>setNotice(''),2800)}
  function choose(p){setSelected(p.id);setPrice(s.listings[p.id]?.price??Math.round(p.cost*2.3));setQty(10)}
  const remaining=Math.max(0,Math.ceil((s.lastTick+TICK_MS-now)/1000)),mm=String(Math.floor(remaining/60)).padStart(2,'0'),ss=String(remaining%60).padStart(2,'0');
  const active=products.filter(p=>s.listings[p.id]?.active&&s.stock[p.id]>0).length,last=s.history.at(-1),selectedProduct=products.find(x=>x.id===selected);
  return <div className="app"><div className="browser"><div className="browserbar"><div className="dots"><i/><i/><i/></div><div className="browser-tabs"><button className={tab==='bank'?'on':''} onClick={()=>setTab('bank')}><Landmark size={15}/> Banco Capivara</button><button className={tab==='market'?'on':''} onClick={()=>setTab('market')}><ShoppingBag size={15}/> Merca Livre</button><button className={tab==='supplier'?'on':''} onClick={()=>setTab('supplier')}><PackageSearch size={15}/> Dragão Express</button></div><div className="address">🔒 mercalivre.game/{tab}</div></div>
    <header className={'sitehead '+tab}><div className="headinner"><div className="brand">{tab==='bank'?'◈ Banco Capivara':tab==='supplier'?'🐉 Dragão Express':'◒ Merca Livre'}<small>{tab==='bank'?'Seu dinheiro, suas decisões':tab==='supplier'?'O mundo cabe no seu depósito':'Seu negócio começa aqui'}</small></div><div className="daybox"><span>CICLO {s.minute}</span><strong>Próximo ciclo: {mm}:{ss}</strong><small>Automático · 1 min</small></div></div></header>
    <div className="content"><aside><div className="side-title">PAINEL DA LOJA</div><div className="stat"><span>Saldo disponível</span><strong>{money(s.cash)}</strong></div><div className="stat"><span>Patrimônio</span><strong>{money(wealth(s))}</strong></div><div className="stat"><span>Depósito</span><strong>{occupied(s)} / {s.capacity}</strong><small>+ {reserved(s)} espaços em trânsito</small><div className="bar"><i style={{width:`${Math.min(100,(occupied(s)+reserved(s))/s.capacity*100)}%`}}/></div></div><div className="stat"><span>Reputação</span><strong><Star size={18} fill="#f8bd48" color="#f8bd48"/> {s.reputation.toFixed(2)}</strong></div><div className="side-title updates">ÚLTIMAS NOTÍCIAS</div><div className="feed">{s.feed.slice(0,6).map((x,i)=><p key={i}>{x}</p>)}</div></aside>
    <main>{tab==='supplier'?<><div className="pageheading"><div><div className="eyebrow">FORNECEDORES INTERNACIONAIS</div><h1>Encontre sua próxima oportunidade.</h1><p>Compre lotes e aguarde a entrega. Depois, anuncie os produtos que chegaram ao depósito.</p></div><div className="pill">🚚 Entrega em minutos</div></div><div className="tip"><Info size={18}/> Demanda e qualidade são estimativas. Os resultados variam a cada ciclo.</div><div className="grid">{products.map(p=><article className="product" key={p.id}><div className="product-icon">{p.emoji}</div><div className="category">{p.category}</div><h3>{p.name}</h3><div className="product-meta"><span>Custo/un.</span><strong>{money(p.cost)}</strong></div><div className="product-meta"><span>Demanda estimada</span><b>{p.trend>1.25?'Alta':p.trend<.9?'Moderada':'Boa'}</b></div><div className="product-meta"><span>Prazo</span><b>{deliveryMinutes(p,s.levels.shipping)} min</b></div><button className="outline full" onClick={()=>choose(p)}>Comprar lote <ArrowRight size={16}/></button></article>)}</div></>:
    tab==='market'?<><div className="pageheading"><div><div className="eyebrow">CENTRAL DO VENDEDOR</div><h1>Seu império começa com um anúncio.</h1><p>Anuncie itens em estoque. A cada minuto, visitantes chegam à sua vitrine e podem comprar.</p></div><div className="pill">{active} anúncio(s) com estoque</div></div><div className="metrics"><div><span>Visitas no último ciclo</span><strong>{last?.visits??0}</strong><small>visitantes</small></div><div><span>Compradores</span><strong>{last?.buyers??0}</strong><small>{last?.sales??0} unidade(s) vendida(s)</small></div><div><span>Receita no ciclo</span><strong>{money(last?.revenue??0)}</strong><small>antes da taxa de 12%</small></div></div><div className="section-title"><h2>Seu estoque e anúncios</h2><button className="primary" onClick={()=>setTab('supplier')}><Plus size={16}/> Comprar produtos</button></div><div className="listing-grid">{products.filter(p=>s.stock[p.id]>0||s.listings[p.id]).map(p=><article className="listing" key={p.id}><span className="listing-icon">{p.emoji}</span><div><h3>{p.name}</h3><p>{s.stock[p.id]||0} em estoque · {s.incoming.filter(o=>o.id===p.id).reduce((a,o)=>a+o.qty,0)} a caminho</p><small>{s.research[p.id]||0} vendidos no total</small></div><div className="listing-price"><strong>{s.listings[p.id]?money(s.listings[p.id].price):'Sem anúncio'}</strong><small>{s.stock[p.id]>0&&s.listings[p.id]?.active?'Publicado':s.stock[p.id]>0?'Pronto para anunciar':'Esgotado'}</small><button className="textbtn" disabled={!s.stock[p.id]} onClick={()=>choose(p)}>{s.listings[p.id]?'Editar anúncio':'Criar anúncio'}</button></div></article>)}</div>{!products.some(p=>s.stock[p.id]>0||s.listings[p.id])&&<div className="empty"><ShoppingBag size={32}/><h3>Sua vitrine está vazia</h3><p>Compre um lote no Dragão Express. Quando chegar, publique o anúncio aqui.</p><button className="primary" onClick={()=>setTab('supplier')}>Explorar fornecedores <ArrowRight size={16}/></button></div>}<div className="section-title"><h2>Entregas em trânsito</h2></div><div className="tablecard">{s.incoming.length?s.incoming.map((o,i)=>{const p=products.find(x=>x.id===o.id);return <div className="row" key={i}><span>{p.emoji} {p.name}</span><span>{o.qty} unidades</span><b>{Math.max(0,Math.ceil((o.eta-now)/60000))} min restantes</b></div>}):<div className="mutedrow">Nenhum pedido em trânsito.</div>}</div></>:
    <><div className="pageheading"><div><div className="eyebrow">BANCO CAPIVARA</div><h1>Invista na sua operação.</h1><p>Acompanhe o caixa e escolha como acelerar o crescimento da loja.</p></div><div className="pill">💳 Conta empresarial</div></div><div className="metrics bankmetrics"><div><span>Saldo disponível</span><strong>{money(s.cash)}</strong></div><div><span>Patrimônio estimado</span><strong>{money(wealth(s))}</strong></div><div><span>Dívida</span><strong>{money(s.debt)}</strong></div></div><div className="upgrade-grid">{Object.entries(upgrades).map(([type,u])=>{const level=s.levels[type],cost=u.costs[level];return <section className="upgrade" key={type}><div className="panel-icon">{type==='shipping'?<Clock3 size={24}/>:<TrendingUp size={24}/>}</div><div><h2>{u.name} <small>Nível {level}/3</small></h2><p>{u.effect}{type==='shipping'?' nos próximos pedidos.':''}</p><button className="primary" disabled={cost==null||s.cash<cost} onClick={()=>act(upgrade,type)}>{cost==null?'Nível máximo':`Investir ${money(cost)}`}</button></div></section>})}</div><div className="bank-panels"><section className="credit"><div className="panel-icon"><TrendingUp size={24}/></div><div><h2>Crédito de recuperação</h2><p>Receba R$ 750 e quite R$ 900 quando tiver caixa.</p><button className="outline" onClick={()=>act(s.debt?repay:loan)} disabled={!!s.debt&&s.cash<s.debt}>{s.debt?`Quitar ${money(s.debt)}`:'Solicitar R$ 750'}</button></div></section></div><div className="section-title"><h2>Extrato</h2></div><div className="tablecard">{s.transactions.slice(0,20).map((t,i)=><div className="row" key={i}><span><small>Ciclo {t.minute??t.day??0}</small>{t.label}</span><b className={t.amount>=0?'positive':'negative'}>{t.amount>=0?'+':''}{money(t.amount)}</b></div>)}</div></>}</main></div>
    <footer>MERCA LIVRE · Um jogo de comércio fictício · Progresso salvo neste navegador <button onClick={()=>{if(confirm('Apagar a partida e começar de novo?')){setS(newGame());setTab('market')}}}><RotateCcw size={13}/> Reiniciar</button></footer></div>
    {selectedProduct&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="modal"><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modal-emoji">{selectedProduct.emoji}</div><span className="category">{selectedProduct.category}</span><h2>{selectedProduct.name}</h2><p className="muted">Custo por unidade: {money(selectedProduct.cost)} · Ocupa {selectedProduct.space} espaço(s) no depósito</p>{tab==='supplier'?<section className="modal-panel"><h3>Comprar do fornecedor</h3><label>Quantidade de unidades<input type="number" min="1" max="200" value={qty} onChange={e=>setQty(e.target.value)}/></label><p className="muted">Frete: {money(28+Math.ceil(Math.max(0,Number(qty))/10)*7)} · Total: {money(selectedProduct.cost*Number(qty)+(28+Math.ceil(Math.max(0,Number(qty))/10)*7))}</p><p className="muted">Prazo: {deliveryMinutes(selectedProduct,s.levels.shipping)} minutos reais.</p><button className="primary full" onClick={()=>act(buy,selectedProduct.id,qty,Date.now())}>Comprar lote</button></section>:<section className="modal-panel"><h3>Publicar no Merca Livre</h3><p className="muted">Disponível: {s.stock[selectedProduct.id]||0} unidade(s)</p><label>Preço de venda (R$)<input type="number" min="1" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><p className="muted">O marketplace cobra 12% sobre as vendas.</p><button className="primary full" onClick={()=>act(listProduct,selectedProduct.id,price)}>{s.listings[selectedProduct.id]?'Salvar anúncio':'Publicar anúncio'}</button></section>}</div></div>}
    {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice}</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
